import { KOL } from "../types/idlTypes";

export const kols: KOL[] = [
  {
    name: "Vitalik Buterin",
    id: "vitalikbuterin",
    age: 25,
    country: "Russia",
    accountCreation: 2011,
    pfp: "/images/vitalik.png",
    followers: 5000000,
    ecosystem: "Chain Founder",
  },
  {
    name: "CZ Binance",
    id: "czbinance",
    age: 45,
    country: "China",
    accountCreation: 2017,
    pfp: "/images/cz.png",
    followers: 5000000,
    ecosystem: "CEX",
  },
  {
    name: "Brian Armstrong",
    id: "brianarmstrong",
    age: 45,
    country: "USA",
    accountCreation: 2008,
    pfp: "/images/brian.png",
    followers: 2000000,
    ecosystem: "CEX",
  },
  {
    name: "Michael Saylor",
    id: "michaelsaylor",
    age: 55,
    country: "USA",
    accountCreation: 2011,
    pfp: "/images/michael.png",
    followers: 4000000,
    ecosystem: "Bitcoin",
  },
  {
    name: "toly us | com",
    id: "tolyuscom",
    age: 45,
    country: "USA; Ukraine",
    accountCreation: 2014,
    pfp: "/images/toly.png",
    followers: 250000,
    ecosystem: "Chain Founder",
  },
  {
    name: "SBF",
    id: "sbf",
    age: 35,
    country: "USA",
    accountCreation: 2019,
    pfp: "/images/sbf.png",
    followers: 550000,
    ecosystem: "CEX",
  },
  {
    name: "Charles Hoskinson",
    id: "charleshoskinson",
    age: 35,
    country: "USA",
    accountCreation: 2013,
    pfp: "/images/charles.png",
    followers: 750000,
    ecosystem: "Chain Founder",
  },
  {
    name: "Emin Gün Sirer",
    id: "emingünsirer",
    age: 45,
    country: "Turkey",
    accountCreation: 2011,
    pfp: "/images/emin.png",
    followers: 250000,
    ecosystem: "Chain Founder",
  },
  {
    name: "Gavin Wood",
    id: "gavinwood",
    age: 45,
    country: "UK",
    accountCreation: 2009,
    pfp: "/images/gavin.png",
    followers: 250000,
    ecosystem: "Chain Founder",
  },
  {
    name: "Pavel Durov",
    id: "paveldurov",
    age: 35,
    country: "Russia",
    accountCreation: 2008,
    pfp: "/images/pavel.png",
    followers: 2000000,
    ecosystem: "Chain Founder",
  },
  {
    name: "Do Kwon",
    id: "dokwon",
    age: 35,
    country: "South Korea",
    accountCreation: 2011,
    pfp: "/images/do.png",
    followers: 750000,
    ecosystem: "Chain Founder",
  },
  {
    name: "Justin Sun",
    id: "justinsun",
    age: 35,
    country: "China",
    accountCreation: 2017,
    pfp: "/images/justin.png",
    followers: 4000000,
    ecosystem: "Chain Founder",
  },
  {
    name: "Zach XBT",
    id: "zachxbt",
    age: 30,
    country: "Unknown",
    accountCreation: 2015,
    pfp: "/images/zach.png",
    followers: 550000,
    ecosystem: "Reporter",
  },
  {
    name: "Layah Heilpern",
    id: "layahheilpern",
    age: 25,
    country: "UK",
    accountCreation: 2012,
    pfp: "/images/layah.png",
    followers: 750000,
    ecosystem: "Reporter, Bitcoin",
  },
  {
    name: "Gary Gensler",
    id: "garygensler",
    age: 65,
    country: "USA",
    accountCreation: 2021,
    pfp: "/images/gary.png",
    followers: 500000,
    ecosystem: "Government",
  },
  {
    name: "Tyler Winklevoss",
    id: "tylerwinklevoss",
    age: 45,
    country: "USA",
    accountCreation: 2009,
    pfp: "/images/tyler.png",
    followers: 750000,
    ecosystem: "CEX",
  },
  {
    name: "Donald Trump",
    id: "donaldtrump",
    age: 75,
    country: "USA",
    accountCreation: 2009,
    pfp: "/images/trump.png",
    followers: 5000000,
    ecosystem: "Government, Bitcoin",
  },
  {
    name: "Satoshi Nakamoto",
    id: "satoshinakamoto",
    age: 0,
    country: "Unknown",
    accountCreation: 0,
    pfp: "/images/satoshi.png",
    followers: 0,
    ecosystem: "Bitcoin",
  },
  {
    name: "Elizabeth Warren",
    id: "elizabethwarren",
    age: 75,
    country: "USA",
    accountCreation: 2011,
    pfp: "/images/elizabeth.png",
    followers: 5000000,
    ecosystem: "Government",
  },
  {
    name: "Jim Cramer",
    id: "jimcramer",
    age: 65,
    country: "USA",
    accountCreation: 2008,
    pfp: "/images/jim.png",
    followers: 2000000,
    ecosystem: "Reporter",
  },
];
