import { KOL } from "@prisma/client";

export type XFollowersRange =
  | "0-50k"
  | "50-100k"
  | "100-200k"
  | "200-300k"
  | "300-500k"
  | "over 500k";

export type AgeRange = "20-30" | "21-30" | "30-40" | "31-40" | "41-50";

export type Ecosystem = "NFTs" | "SOLANA" | "Founder" | "Influencer";

export const rawKOL: Omit<KOL, "createdAt" | "updatedAt">[] = [
  {
    name: "Frank",
    age: 25,
    twitterHandle: "frankdegods",
    pfpType: "Artificial",
    country: "USA",
    pfp: "https://res.cloudinary.com/dbuaprzc0/image/upload/v1728170407/Soddle-Solana/hu7kprxwmuzjnwdqhgia.jpg",
    twitterAccountCreationYear: 2021,
    followers: 250000,
    ecosystem: "NFTs",
    tweets: [
      "Just to be explicit because apparently a lot of people are saying this:\nNo, we are not planning to acquire Huobi.",
      "Somehow it makes me really happy that @TomBrady's first play of his 45\nyear old season wasn't just a 24y pass--it was a clever, well-orchestrated\npass for 24 YAC.",
      "1) I'm sorry. That's the biggest thing.\nI fucked up, and should have done better.",
      "1) A competitor is trying to go after us\nwith false rumors.\nFTX is fine. Assets are fine.\nDetails:",
    ],
    descriptions: [
      "Inventor of the paper hand bitch tax.",
      "Paved the way for NFTs on Solana. Got lost on his own way and moved to Ethereum, now back though.",
      "A brave man, was wearing sweatpants at the Iggy party.",
    ],
    supportedChains: ["solana"],
    id: "66e73ef703e3b6308e74f1a1",
    ageRange: "21-30",
    twitterFollowersRange: "200-300k",
  },
  {
    name: "Lily Liu",
    twitterHandle: "calilyliu",
    pfpType: "Human",
    age: 35,
    country: "Switzerland",
    pfp: "https://res.cloudinary.com/dbuaprzc0/image/upload/v1728170548/Soddle-Solana/t6rkninhw6w0fmm8qjnv.jpg",
    twitterAccountCreationYear: 2009,
    followers: 25000,
    ecosystem: "Solana",
    tweets: [
      "7 years ago, before ethereum even\nbegan, I had only a few thousand dollars\nof net worth. I nevertheless sold half my\nbitcoin to make sure that I would not be\nbroke if BTC went to zero.",
      'Against choosing your political allegiances based on who is "pro-crypto',
      "7 years ago, before ethereum even began, I had only a few thousand\ndollars of net worth. I nevertheless sold half my bitcoin to make sure that\nI would not be broke if BTC went to zero.",
      'If all that we accomplish is lambo\nmemes and immature puns about\n"sharting", then I WILL leave.\nThough I still have a lot of hope that the\ncommunity can steer in the right\ndirection.',
      "The 'metaverse' is going to happen but I don't think any of the existing corporate attempts to intentionally create the metaverse are going anywhere.",
    ],
    descriptions: [
      "Will go down in the history books as first president of Solana.",
      "Working three jobs at the same time, role model for all Asians.",
      "Probably an unsung hero, pulling all the Solana strings.",
    ],
    supportedChains: ["solana"],
    id: "66e73ef703e3b6308e74f19c",
    ageRange: "31-40",
    twitterFollowersRange: "0-50k",
  },
  {
    name: "Austin Federa",
    age: 35,
    twitterHandle: "austin_federa",
    pfpType: "Artificial",
    country: "USA",
    pfp: "https://res.cloudinary.com/dbuaprzc0/image/upload/v1728170674/Soddle-Solana/phtxcexfiqaml54bzcuz.jpg",
    twitterAccountCreationYear: 2009,
    followers: 150000,
    ecosystem: "Solana",
    tweets: [
      "2/ I understand the last 72 hours have been extremely tough on all of you -\nknow that I am resolved to work with every one of you to weather this crisis,\nand we will build our way out of this.\nTogether.",
      "I don't debate the poor on Twitter, and sorry I don't\nhave any change on me for her at the moment.",
      "So, is this SUST depeg in the room with us right now?\nI prescribe 24 hours of pegging over the next 7 days",
      "By my hand $DAI will die",
      "Deploying more capital - steady lads",
    ],
    descriptions: [
      "Spends more than three hours a day to make his hair- it does look good though.",
      "Giving American Psycho vibes, let's hope he's a good guy.",
      "Big brain, big smile.",
    ],
    supportedChains: ["solana"],
    id: "66e73ef703e3b6308e74f1a6",
    ageRange: "31-40",
    twitterFollowersRange: "100-200k",
  },
  {
    name: "Kash Danda",
    twitterHandle: "kashdhanda",
    pfpType: "Artificial",
    age: 35,
    country: "UK",
    pfp: "https://res.cloudinary.com/dbuaprzc0/image/upload/v1728170850/Soddle-Solana/mwhtb1uwe1o8mfaco1az.jpg",
    twitterAccountCreationYear: 2013,
    followers: 25000,
    ecosystem: "Solana",
    tweets: [
      "Communication is the clothing of the consciousness",
      "CZ on SBF:\"No one can protect [from] a bad player, to be very frank, if a guy\nis very good at lying, and very good at just pretending to be what he's not.\"\nNot been paying attention? Protection comes thru decentralisation. That's\nthe point of web3 and trustless tech. @cz_binance",
      "AI: More trust, less truth",
      "It's not fair that Solana's market cap\npassed Polkadot. I've been working on\nPolkadot for A LOT longer. I even made\neverything about Polkadot extremely\ncomplicated. That means better, right?\nDon't they know who I am? I'm one of the\nfounders of Ethereum. F** * Solana.",
      "If you post a DOT address I'll personally contribute $5m",
    ],
    descriptions: [
      "Built an army of Solana maxis all around the world.",
      "Hands down the best Solana updates, go watch the Solana Ecosystem Call on YouTube.",
      "Has friends in every country (as long as there's a Superteam).",
    ],
    supportedChains: ["solana"],
    id: "66e73ef703e3b6308e74f1a4",
    ageRange: "31-40",
    twitterFollowersRange: "0-50k",
  },
  {
    name: "Nom",
    age: 45,
    twitterHandle: "theonlynom",
    pfpType: "Artificial",
    country: "USA",
    pfp: "https://res.cloudinary.com/dbuaprzc0/image/upload/v1728170972/Soddle-Solana/rxxkptorkedicswj9bzz.jpg",
    twitterAccountCreationYear: 2011,
    followers: 75000,
    ecosystem: "NFTs",
    tweets: [
      "Hamas raised millions via crypto in the months leading up to their attack\non Israel. @RogerMarshallMD, @RepCasten and I are leading 100+\nlawmakers urging the Biden admin to address crypto-financed terrorism.",
      "A new @USGAO\nreport confirms that rogue nations are using crypto to\ndodge sanctions and undermine our national security.\nIt's time for crypto to follow the same anti-money laundering rules as\neveryone else. I've got a bill to make it happen.",
      "The\n@SECgov is wrong on the law and wrong on the policy with respect\nto the Bitcoin ETF decision.\nIf the SEC is going to let crypto burrow even deeper into our financial\nsystem, then it's more urgent than ever that crypto follow basic anti-\nmoney laundering rules.",
      "Bitcoin requires so much computing activity that it eats\nup more energy than entire countries. One of the\neasiest and least disruptive things we can do to fight\nthe #ClimateCrisis is to crack down on environmentally\nwasteful c tocurrencies.",
      "Let's change the rigged tax code so The Person of the\nYear will actually pay taxes and stop freeloading off\nA.er.yqne,else.",
    ],
    descriptions: [
      "Likes monkes and dogs.",
      "Responsible for arguably the best airdrop in crypto history.",
      "BONK BONK BONK BONK BONK",
    ],
    supportedChains: ["solana"],
    id: "66e73ef703e3b6308e74f1ae",
    ageRange: "41-50",
    twitterFollowersRange: "50-100k",
  },
  {
    name: "meow",
    age: 45,
    twitterHandle: "weremeow",
    pfpType: "Artificial",
    country: "Singapore",
    pfp: "https://res.cloudinary.com/dbuaprzc0/image/upload/v1728171082/Soddle-Solana/fpoqwwioycfsogym77uq.jpg",
    twitterAccountCreationYear: 2008,
    followers: 750000,
    ecosystem: "Founder",
    tweets: [],
    descriptions: [
      "Named himself after a cat, his company after a planet.",
      "Watch his interview with Luke Belmar if you're trying to lose brain cells.",
      "Built arguably the best DEX in the world.",
    ],
    supportedChains: ["solana"],
    id: "66e73ef703e3b6308e74f1a9",
    ageRange: "41-50",
    twitterFollowersRange: "over 500k",
  },
  {
    name: "toly 🇺🇸 | compressed",
    twitterHandle: "aeyakovenko",
    pfpType: "Artificial",
    age: 45,
    country: "USA; Ukraine",
    pfp: "https://res.cloudinary.com/dbuaprzc0/image/upload/f_auto,q_auto/v1/Soddle/quuaczmi0kyobewixkqr",
    twitterAccountCreationYear: 2014,
    followers: 450000,
    ecosystem: "Solana, Founder",
    tweets: [
      "Solana is ethereum! Solana is an ethereum L2 through the wormhole\neigenlayer. Once danksharding is scaled up no one is going to stop you\nfrom submitting all the solana blocks into some data validating bridge\ncontract on ethereum",
      "Someone should build an anti-Amazon. All the items are free and donated,\nbut you pay for shipping. With 3 kids, I clear out a truck full of stuff to\ngoodwill every month. I'd rather get magic tokens for it.",
      "If the state is against ethereum then I am against the state",
      "F' these anti-Semitic racist incels",
      "I think that a DAO that only has the authority to mint more coins is the\nclosest thing to a uasf power of the LI.\n1) No treasury => nothing of value to steal\n2) if the quorum goes rogue community can simply fork and slash the\nmalicious part of the quorum.",
    ],
    descriptions: [
      "Cosplayer turned Crypto Founder.",
      "The best things happen after two coffee and a beer.",
      "The hat stays on.",
    ],
    supportedChains: ["solana"],
    id: "66e73ef703e3b6308e74f1a0",
    ageRange: "41-50",
    twitterFollowersRange: "300-500k",
  },
  {
    name: "mert",
    age: 35,
    twitterHandle: "0xMert_",
    pfpType: "Artificial",
    country: "Canada",
    pfp: "https://pbs.twimg.com/profile_images/1775535430835863552/zgFeCArT_400x400.jpg",
    twitterAccountCreationYear: 2017,
    followers: 150000,
    ecosystem: "Founder",
    tweets: [
      "Ethereum is a decentralized protocol, and we are ordinary participants in\nEthereum. We have sufficient capital to provide TVL, node verification\nservices for Ethereum, Tron, and all other types of L2 projects to secure all\nblockchains. We are here for the long-term building.",
      "China also needs to step up. Since President Trump pushed for Bitcoin,\nU.S. policies have warmed. China should make further progress in this\narea. Competition between China and the U.S. in Bitcoin policy will benefit\nthe entire industry.",
      "I am willing to negotiate with the German government to purchase all BTC\noff-market in order to minimize the impact on the market.",
      "Our team is developing a new solution that enables gas-free stablecoin\ntransfers. In other words, transfers can be made without paying any gas\ntokens, with the fees being entirely covered by the stablecoins\nthemselves.",
    ],
    descriptions: [
      "Egghead. (all jokes aside: jacked, smart and rich. We're all jealous)",
      "*insert a bald joke*",
      "Big head for a lot of brains, bebe.",
    ],
    supportedChains: ["solana"],
    id: "66e73ef703e3b6308e74f1a7",
    ageRange: "31-40",
    twitterFollowersRange: "100-200k",
  },
  {
    name: "Armani Ferrante",
    age: 35,
    twitterHandle: "armaniferrante",
    pfpType: "Human",
    country: "USA",
    pfp: "https://res.cloudinary.com/dbuaprzc0/image/upload/v1728171948/Soddle-Solana/nak9efeqpxq8qhxhmcng.jpg",
    twitterAccountCreationYear: 2011,
    followers: 75000,
    ecosystem: "NFTs,Founder",
    tweets: [
      "The blockchain industry was built on the promise of decentralization, but\nended up being concentrated in the hands of a few who began to abuse\ntheir power.",
      "I guess there's a billion people on this planet wishing to move to Germany. If\nI were Germany, I would select the top .196 of them via tests.",
      '8096 of the people introduced to me by an e-mail want to "jump on a phone\ncall". I never do phone calls. It\'s obsolete and intrusive.',
      "I am not a 'permanent resident of Finland'. The fact that I'm using a Finnish\nmail address confuses some journalists.",
    ],
    descriptions: [
      "Favourite accessoire is a backpack.",
      "Lost 90% in the FTX crash, came back stronger than ever before.",
      "Had five different haircuts in the last two years, looks good in all of them.",
    ],
    supportedChains: ["solana"],

    id: "66e73ef703e3b6308e74f1a5",
    ageRange: "31-40",
    twitterFollowersRange: "50-100k",
  },
  {
    name: "raj",
    age: 45,
    twitterHandle: "rajgokal",
    pfpType: "Artificial",
    country: "USA",
    pfp: "https://res.cloudinary.com/dbuaprzc0/image/upload/v1728173435/Soddle-Solana/soddle/Solana%20PFPs/zjnjjgj3vmn3lnuldu8p.jpg",
    twitterAccountCreationYear: 2010,
    followers: 250000,
    ecosystem: "Solana, Founder",
    tweets: [
      "We're all in it for the $tech",
      'Hey y \'all, We all ignored the huge red flags associated with SBF because "he looked smart" and "he made a lot of money." Then it turned out that he was dumb as rocks, was a sociopath, and was just stealing our money. The next cycle is going to be even more noisy, with even Show more',
      'PSA: "l hate crypto, it\'s all scams" and I\'l hate the way banks charge high\nfees" are the same person.',
      "These scams are getting out of hand.\n@jack, @twitter, if you can't detect this\nkind of brazen scam, what hope do you\nhave of improving your platform?\ntwitter.com/Leonov6236Vova...",
      "There's an ongoing attack targeting the Solana ecosystem right now.\n7000+ wallets affected, and rising at 20/min. Because it's very early and\nthe attack is ongoing, there's 8 lot of misinformation and speculation. So\nhere are a few thoughts and clarifications.",
    ],
    descriptions: [
      "Has the best PFP on Crypto Twitter.",
      "Founder with the best humour, man of the people!",
      "raj&toly = yin&yang",
    ],
    supportedChains: ["solana"],
    id: "66e73ef703e3b6308e74f1a3",
    ageRange: "41-50",
    twitterFollowersRange: "200-300k",
  },
  {
    name: "Ansem",
    twitterHandle: "blknoiz06",
    pfpType: "Artificial",
    age: 25,
    country: "USA",
    pfp: "https://res.cloudinary.com/dbuaprzc0/image/upload/v1728173434/Soddle-Solana/soddle/Solana%20PFPs/wege2tz4uxuio4w887ev.jpg",
    twitterAccountCreationYear: 2012,
    followers: 550000,
    ecosystem: "Influencer",
    tweets: [
      "When the titanic sinks, little floats near it get dragged down too. But the\nfloats will eventually come back up, if they are untethered.",
      "Slap yourself,\n$BTC under $10 000.\nif ou sold",
      "e need less divide in the world. More building.",
      "Will try to keep 2023 simple. Spen\nDon'ts.\n1. Education\n2. Compliance\n3. Product & Service\nmore time on esst ings. Dos an\n4. Ignore FUD, fake news, attacks, etc.\nIn the future, would appreciate if you can link to this post when I tweet",
      "Sad day. Tried, but 😭",
      "I you o ow a nc crazy ran omy swinging person's\ntweets to trade, you will end up ... not rich.\nNFA.",
    ],
    descriptions: [
      "Can't decide if he's a founder, influencer, boxer or trader.",
      "Very tall guy.",
      "A little weird at times, but who are we to judge.",
    ],
    supportedChains: ["solana"],
    id: "66e73ef703e3b6308e74f19d",
    ageRange: "21-30",
    twitterFollowersRange: "over 500k",
  },
  {
    name: "Jakey",
    age: 25,
    twitterHandle: "soljakey",
    pfpType: "Artificial",
    country: "Canada",
    pfp: "https://res.cloudinary.com/dbuaprzc0/image/upload/v1728173434/Soddle-Solana/soddle/Solana%20PFPs/s0wj2nyqgfrlzxibbe5y.jpg",
    twitterAccountCreationYear: 2022,
    followers: 150000,
    ecosystem: "Influencer, NFTs",
    tweets: [
      "Remember this: gold held up a lot better than crypto",
      "As i predict another weak year for crypto, i do ponder\nhow many people are still involved, now many millions\nof people....",
      "I will admit I was wrong about Bitcoin. 100k seems to be in the cards QI",
      "As far as crypto, same: i bought a farm with my Bitcoin\nwinnings, all announced, and i bought a boat with\nEthereum. All announced. Everything disclosed. I\nWANT you to bet against me. You do not do this for 42\nyears and lose money evert year.",
      "Unlikely that Bitcoin finds it's footing",
    ],
    descriptions: [
      "A little weird but we like him.",
      "Could be Steve-O's son.",
      "Has the highest output in whole Crypto Twitter.",
    ],
    supportedChains: ["solana"],
    id: "66e73ef703e3b6308e74f1af",
    ageRange: "21-30",
    twitterFollowersRange: "100-200k",
  },
  {
    name: "KSI",
    age: 35,
    twitterHandle: "ksicrypto",
    pfpType: "Artificial",
    country: "UK",
    pfp: "https://res.cloudinary.com/dbuaprzc0/image/upload/v1728173436/Soddle-Solana/soddle/Solana%20PFPs/a7ej8lqlpsgg7616jcvl.jpg",
    twitterAccountCreationYear: 2021,
    followers: 450000,
    ecosystem: "Influencer",
    tweets: [
      "So that's what you do with 4 billion dollars",
      "Hulk just ripped his shirt off. The 80s are back kids",
      "Alright, team blue, now is a wonderful time to reset the ticket and pick\nsomeone who is pro-crypto. Let's make crypto a bipartisan issue and undo\nthe mistakes of the Biden administration",
      "I never thought I'd tweet this...l'm rejoining\nEthereum to start making contributions to\nClassic. Will report more later",
      "'You're telling the CEO of iohk, founder of\ncardano and ethereum to use the support\nemail? Just wanted to ask about the chrome\ndelisting.",
    ],
    descriptions: [
      "Has no idea what he's doing.",
      "Not the same since he doesn't have the SMB PFP anymore.",
      "Can't decide whether he's bullish or bearish.",
    ],
    supportedChains: ["solana"],
    id: "66e73ef703e3b6308e74f1a2",
    ageRange: "31-40",
    twitterFollowersRange: "300-500k",
  },
  {
    name: "Iggy",
    age: 35,
    twitterHandle: "IGGYAZALEA",
    pfpType: "Human",
    country: "Australia",
    pfp: "https://res.cloudinary.com/dbuaprzc0/image/upload/v1728173437/Soddle-Solana/soddle/Solana%20PFPs/wvz3u3a4ol51v0odrrpt.jpg",
    twitterAccountCreationYear: 2010,
    followers: 750000,
    ecosystem: "Influencer",
    tweets: [
      "2/6 Most alarming to me is how the WorldCoin team has boasted about\nhow many users they have.\nWhen in reality they have been exploiting people in developing countries.\ntechnologyreview.com/2022/04/06/104...",
      "Hello @MarioNawfal why is my name appearing in a deck to shill your\nmarketing services when I have never done paid promotions or spoken with\nyour IBC team?\nUnless you count my services as the times I called you out for spreading\nmisinformation during the FTX incident.",
      'Remember when KSI posted\n"All of a sudden, my $XCAD bag is looking juicy again. #HodlGang"\nThen proceeded to dump $850,000 worth of XCAD over the following days\nfrom his wallet address.',
      'Remember when KSI posted\n"All of a sudden, my $XCAD bag is looking juicy again. #HodlGang"\nThen proceeded to dump $850,000 worth of XCAD over the following days\nfrom his wallet address.',
      "Proud to share that earlier this year I helped lead an initiative which\nresulted in the successful seizure of S12M connected to the Caesar's\nransomware incident from September 2023.\nThis was done in collaboration with @RussellKlein and law enforcement.",
    ],
    descriptions: [
      "Used to be a mid rapper, now a top tier memecoin founder.",
      "The only celebrity that launched a memecoin and didn't rug.",
      "Trying to make crypto mainstream in her own way, you gotta respect it.",
    ],
    supportedChains: ["solana"],
    id: "66e73ef703e3b6308e74f1a8",
    ageRange: "31-40",
    twitterFollowersRange: "over 500k",
  },
  {
    name: "vibhu",
    age: 35,
    twitterHandle: "vibhu",
    pfpType: "Artificial",
    country: "India",
    pfp: "https://res.cloudinary.com/dbuaprzc0/image/upload/v1728173434/Soddle-Solana/soddle/Solana%20PFPs/juylmlxv6wezrwcd9ecy.jpg",
    twitterAccountCreationYear: 2008,
    followers: 25000,
    ecosystem: "Founder",
    tweets: [
      "Let's talk digital engagement practices.\nPredictive data analytics & Al are transforming so much of our economy.\nFinance is no exception.\nAl already is being used for call centers, account openings, compliance\nprograms, trading algorithms, & sentiment analysis, among others.",
      "If your friend, family member, or coworker encouraged you to invest in an\nopportunity guaranteed to pay at least IO percent returns, what would you\nLearn more about affinity fraud and what you can do to avoid it:\ninvestor.gov/protect-your-i...",
      "A thread\nSome things to keep in mind if you're considering investing in crypto\nassets:",
      "Coinbase's alleged failures deprive investors of critical protections,\nincluding rulebooks that prevent fraud and manipulation, proper\ndisclosure, safeguards against conflicts of interest, and routine\ninspection by the SEC.",
      "The @SECGov\ntwitter account was\ncompromised, and an unauthorized tweet was\nposted. The SEC has not approved the listing\nand trading of spot bitcoin exchange-traded\nproducts.",
    ],
    descriptions: [
      "Has a lot of drip.",
      "In it for the art.",
      "Not into tokens or DeFi. NGMI except he already made it.",
    ],
    supportedChains: ["solana"],
    id: "66e73ef703e3b6308e74f1aa",
    ageRange: "31-40",
    twitterFollowersRange: "0-50k",
  },
];
